/* Generated by JTB 1.4.7 */
package msmb.parsers.mathExpression.syntaxtree;

import msmb.parsers.mathExpression.visitor.*;

/**
 * JTB node class for the production SiteSelector_postFix:<br>
 * Corresponding grammar:<br>
 * nodeToken -> <LBRACE><br>
 * expression -> Expression()<br>
 * nodeOptional -> ( %0 ( #0 <COMMA><br>
 * ............ .. . .. . #1 ( &0 Name()<br>
 * ............ .. . .. . .. | &1 Literal() ) )+<br>
 * ............ .. | %1 ( #0 <COLON> #1 Expression() ) )?<br>
 * nodeToken1 -> <RBRACE><br>
 */
public class SiteSelector_postFix implements INode {

  /** Child node 1 */
  public NodeToken nodeToken;

  /** Child node 2 */
  public Expression expression;

  /** Child node 3 */
  public NodeOptional nodeOptional;

  /** Child node 4 */
  public NodeToken nodeToken1;

  /** The serial version UID */
  private static final long serialVersionUID = 147L;

  /**
   * Constructs the node with all its children nodes.
   *
   * @param n0 - first child node
   * @param n1 - next child node
   * @param n2 - next child node
   * @param n3 - next child node
   */
  public SiteSelector_postFix(final NodeToken n0, final Expression n1, final NodeOptional n2, final NodeToken n3) {
    nodeToken = n0;
    expression = n1;
    nodeOptional = n2;
    nodeToken1 = n3;
  }

  /**
   * Accepts the IRetArguVisitor visitor.
   *
   * @param <R> the user return type
   * @param <A> the user argument type
   * @param vis - the visitor
   * @param argu - a user chosen argument
   * @return a user chosen return information
   */
  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  /**
   * Accepts the IRetVisitor visitor.
   *
   * @param <R> the user return type
   * @param vis - the visitor
   * @return a user chosen return information
   */
  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  /**
   * Accepts the IVoidArguVisitor visitor.
   *
   * @param <A> the user argument type
   * @param vis - the visitor
   * @param argu - a user chosen argument
   */
  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  /**
   * Accepts the IVoidVisitor visitor.
   *
   * @param vis - the visitor
   */
  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
