/* Generated By:JavaCC: Do not edit this line. MR_MultistateSpecies_ParserConstants.java */
package msmb.parsers.multistateSpecies;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MR_MultistateSpecies_ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TIME = 6;
  /** RegularExpression Id. */
  int SUM = 7;
  /** RegularExpression Id. */
  int FLOOR = 8;
  /** RegularExpression Id. */
  int SQRT = 9;
  /** RegularExpression Id. */
  int LOG = 10;
  /** RegularExpression Id. */
  int SUCC = 11;
  /** RegularExpression Id. */
  int PREC = 12;
  /** RegularExpression Id. */
  int CIRCULAR_FLAG = 13;
  /** RegularExpression Id. */
  int BLANK = 14;
  /** RegularExpression Id. */
  int OPEN_R = 15;
  /** RegularExpression Id. */
  int CLOSED_R = 16;
  /** RegularExpression Id. */
  int OPEN_C = 17;
  /** RegularExpression Id. */
  int CLOSED_C = 18;
  /** RegularExpression Id. */
  int RANGE_SEPARATOR = 19;
  /** RegularExpression Id. */
  int SITE_NAMES_SEPARATOR = 20;
  /** RegularExpression Id. */
  int SITE_STATES_SEPARATOR = 21;
  /** RegularExpression Id. */
  int STRING_LITERAL = 22;
  /** RegularExpression Id. */
  int NUMBER = 23;
  /** RegularExpression Id. */
  int MULTI_IDENTIFIER = 24;
  /** RegularExpression Id. */
  int MATH_ELEMENT = 25;
  /** RegularExpression Id. */
  int UNDEFINED_SITE_SYMBOL = 26;
  /** RegularExpression Id. */
  int EXTENSION_CONC = 27;
  /** RegularExpression Id. */
  int EXTENSION_PARTICLE = 28;
  /** RegularExpression Id. */
  int EXTENSION_TRANS = 29;
  /** RegularExpression Id. */
  int EXTENSION_INIT = 30;
  /** RegularExpression Id. */
  int EXTENSION_RATE = 31;
  /** RegularExpression Id. */
  int EXTENSION_SPECIES = 32;
  /** RegularExpression Id. */
  int EXTENSION_GLOBALQ = 33;
  /** RegularExpression Id. */
  int EXTENSION_COMPARTMENT = 34;
  /** RegularExpression Id. */
  int EXTENSION_REACTION = 35;
  /** RegularExpression Id. */
  int EXTENSION_FUNCTION = 36;
  /** RegularExpression Id. */
  int EXTENSION_FLUX = 37;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 4>",
    "<token of kind 5>",
    "\"Time\"",
    "\"SUM\"",
    "\"floor\"",
    "\"sqrt\"",
    "\"log\"",
    "\"succ\"",
    "\"pred\"",
    "\"c\"",
    "\" \"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "<STRING_LITERAL>",
    "<NUMBER>",
    "<MULTI_IDENTIFIER>",
    "<MATH_ELEMENT>",
    "\"?\"",
    "\".conc\"",
    "\".part\"",
    "\".trans\"",
    "\".init\"",
    "\".rate\"",
    "\".spc\"",
    "\".glq\"",
    "\".cmp\"",
    "\".rct\"",
    "\".fnc\"",
    "\".flux\"",
    "\"=\"",
    "\".\"",
  };

}
