package msmb.commonUtilities;

public enum MSMB_Element
{
		FONT,
		SPECIES,
		GLOBAL_QUANTITY,
		COMPARTMENT,
		MODEL_NAME,
		MODEL_DEFINITION,
		SELECTED_SPECIES,
		SELECTED_GLOBAL_QUANTITY,	
		SOMETHING_CHANGED,
		DONE_WITH_CHANGES,
		CANCEL;
}
