package acgui;

public class Constants
{
	public static final String TOOL_NAME = new String("JCMC");
	public static final String TOOL_NAME_FULL = "JigCell Model Connector (JCMC)";
	public static final String RECENT_FILE_NAME = new String(TOOL_NAME + "_recents.cfg");
	
	public static final String SOURCE_STANDARD = "source_standard";
	public static final String SOURCE_NORTH = "source_north";
	public static final String SOURCE_SOUTH = "source_south";
	public static final String SOURCE_EAST = "source_east";
	public static final String SOURCE_WEST = "source_west";
	public static final String TARGET_NORTH = "target_north";
	public static final String TARGET_SOUTH = "target_south";
	public static final String TARGET_EAST = "target_east";
	public static final String TARGET_WEST = "target_west";
	public static final String TARGET_STANDARD = "target_standard";
	public static final String SOLID_EDGE = "solid_edge";
	public static final String DASHED_EDGE = "dashed_edge";
	public static final String MINI = "mini";
	
	public static final String SOURCE_NORTH_MODULE_TARGET_STANDARD_SOLID_EDGE = SOURCE_NORTH + "_module_" + TARGET_STANDARD + "_" + SOLID_EDGE;
	public static final String SOURCE_SOUTH_MODULE_TARGET_STANDARD_SOLID_EDGE = SOURCE_SOUTH + "_module_" + TARGET_STANDARD + "_" + SOLID_EDGE;
	public static final String SOURCE_EAST_MODULE_TARGET_STANDARD_SOLID_EDGE = SOURCE_EAST + "_module_" + TARGET_STANDARD + "_" + SOLID_EDGE;
	public static final String SOURCE_WEST_MODULE_TARGET_STANDARD_SOLID_EDGE = SOURCE_WEST + "_module_" + TARGET_STANDARD + "_" + SOLID_EDGE;

	public static final String SOURCE_STANDARD_TARGET_NORTH_MODULE_SOLID_EDGE = SOURCE_STANDARD + "_" + TARGET_NORTH + "_module_" + SOLID_EDGE;
	public static final String SOURCE_STANDARD_TARGET_SOUTH_MODULE_SOLID_EDGE = SOURCE_STANDARD + "_" + TARGET_SOUTH + "_module_" + SOLID_EDGE;
	public static final String SOURCE_STANDARD_TARGET_EAST_MODULE_SOLID_EDGE = SOURCE_STANDARD + "_" + TARGET_EAST + "_module_" + SOLID_EDGE;
	public static final String SOURCE_STANDARD_TARGET_WEST_MODULE_SOLID_EDGE = SOURCE_STANDARD + "_" + TARGET_WEST + "_module_" + SOLID_EDGE;

	public static final String SOURCE_NORTH_SUBMODULE_TARGET_STANDARD_SOLID_EDGE = SOURCE_NORTH + "_submodule_" + TARGET_STANDARD + "_" + SOLID_EDGE;
	public static final String SOURCE_SOUTH_SUBMODULE_TARGET_STANDARD_SOLID_EDGE = SOURCE_SOUTH + "_submodule_" + TARGET_STANDARD + "_" + SOLID_EDGE;
	public static final String SOURCE_EAST_SUBMODULE_TARGET_STANDARD_SOLID_EDGE = SOURCE_EAST + "_submodule_" + TARGET_STANDARD + "_" + SOLID_EDGE;
	public static final String SOURCE_WEST_SUBMODULE_TARGET_STANDARD_SOLID_EDGE = SOURCE_WEST + "_submodule_" + TARGET_STANDARD + "_" + SOLID_EDGE;

	public static final String SOURCE_STANDARD_TARGET_NORTH_SUBMODULE_SOLID_EDGE = SOURCE_STANDARD + "_" + TARGET_NORTH + "_submodule_" + SOLID_EDGE;
	public static final String SOURCE_STANDARD_TARGET_SOUTH_SUBMODULE_SOLID_EDGE = SOURCE_STANDARD + "_" + TARGET_SOUTH + "_submodule_" + SOLID_EDGE;
	public static final String SOURCE_STANDARD_TARGET_EAST_SUBMODULE_SOLID_EDGE = SOURCE_STANDARD + "_" + TARGET_EAST + "_submodule_" + SOLID_EDGE;
	public static final String SOURCE_STANDARD_TARGET_WEST_SUBMODULE_SOLID_EDGE = SOURCE_STANDARD + "_" + TARGET_WEST + "_submodule_" + SOLID_EDGE;

	public static final String SOURCE_NORTH_MODULE_TARGET_STANDARD_DASHED_EDGE = SOURCE_NORTH + "_module_" + TARGET_STANDARD + "_" + DASHED_EDGE;
	public static final String SOURCE_SOUTH_MODULE_TARGET_STANDARD_DASHED_EDGE = SOURCE_SOUTH + "_module_" + TARGET_STANDARD + "_" + DASHED_EDGE;
	public static final String SOURCE_EAST_MODULE_TARGET_STANDARD_DASHED_EDGE = SOURCE_EAST + "_module_" + TARGET_STANDARD + "_" + DASHED_EDGE;
	public static final String SOURCE_WEST_MODULE_TARGET_STANDARD_DASHED_EDGE = SOURCE_WEST + "_module_" + TARGET_STANDARD + "_" + DASHED_EDGE;

	public static final String SOURCE_STANDARD_TARGET_NORTH_MODULE_DASHED_EDGE = SOURCE_STANDARD + "_" + TARGET_NORTH + "_module_" + DASHED_EDGE;
	public static final String SOURCE_STANDARD_TARGET_SOUTH_MODULE_DASHED_EDGE = SOURCE_STANDARD + "_" + TARGET_SOUTH + "_module_" + DASHED_EDGE;
	public static final String SOURCE_STANDARD_TARGET_EAST_MODULE_DASHED_EDGE = SOURCE_STANDARD + "_" + TARGET_EAST + "_module_" + DASHED_EDGE;
	public static final String SOURCE_STANDARD_TARGET_WEST_MODULE_DASHED_EDGE = SOURCE_STANDARD + "_" + TARGET_WEST + "_module_" + DASHED_EDGE;

	public static final String SOURCE_NORTH_SUBMODULE_TARGET_STANDARD_DASHED_EDGE = SOURCE_NORTH + "_submodule_" + TARGET_STANDARD + "_" + DASHED_EDGE;
	public static final String SOURCE_SOUTH_SUBMODULE_TARGET_STANDARD_DASHED_EDGE = SOURCE_SOUTH + "_submodule_" + TARGET_STANDARD + "_" + DASHED_EDGE;
	public static final String SOURCE_EAST_SUBMODULE_TARGET_STANDARD_DASHED_EDGE = SOURCE_EAST + "_submodule_" + TARGET_STANDARD + "_" + DASHED_EDGE;
	public static final String SOURCE_WEST_SUBMODULE_TARGET_STANDARD_DASHED_EDGE = SOURCE_WEST + "_submodule_" + TARGET_STANDARD + "_" + DASHED_EDGE;

	public static final String SOURCE_STANDARD_TARGET_NORTH_SUBMODULE_DASHED_EDGE = SOURCE_STANDARD + "_" + TARGET_NORTH + "_submodule_" + DASHED_EDGE;
	public static final String SOURCE_STANDARD_TARGET_SOUTH_SUBMODULE_DASHED_EDGE = SOURCE_STANDARD + "_" + TARGET_SOUTH + "_submodule_" + DASHED_EDGE;
	public static final String SOURCE_STANDARD_TARGET_EAST_SUBMODULE_DASHED_EDGE = SOURCE_STANDARD + "_" + TARGET_EAST + "_submodule_" + DASHED_EDGE;
	public static final String SOURCE_STANDARD_TARGET_WEST_SUBMODULE_DASHED_EDGE = SOURCE_STANDARD + "_" + TARGET_WEST + "_submodule_" + DASHED_EDGE;

	public static final String SOURCE_NORTH_MODULE_TARGET_STANDARD_SOLID_EDGE_MINI = SOURCE_NORTH_MODULE_TARGET_STANDARD_SOLID_EDGE + "_" + MINI;
	public static final String SOURCE_SOUTH_MODULE_TARGET_STANDARD_SOLID_EDGE_MINI = SOURCE_SOUTH_MODULE_TARGET_STANDARD_SOLID_EDGE + "_" + MINI;
	public static final String SOURCE_EAST_MODULE_TARGET_STANDARD_SOLID_EDGE_MINI = SOURCE_EAST_MODULE_TARGET_STANDARD_SOLID_EDGE + "_" + MINI;
	public static final String SOURCE_WEST_MODULE_TARGET_STANDARD_SOLID_EDGE_MINI = SOURCE_WEST_MODULE_TARGET_STANDARD_SOLID_EDGE + "_" + MINI;
	
	public static final String SOURCE_STANDARD_TARGET_NORTH_MODULE_SOLID_EDGE_MINI = SOURCE_STANDARD_TARGET_NORTH_MODULE_SOLID_EDGE + "_" + MINI;
	public static final String SOURCE_STANDARD_TARGET_SOUTH_MODULE_SOLID_EDGE_MINI = SOURCE_STANDARD_TARGET_SOUTH_MODULE_SOLID_EDGE + "_" + MINI;
	public static final String SOURCE_STANDARD_TARGET_EAST_MODULE_SOLID_EDGE_MINI = SOURCE_STANDARD_TARGET_EAST_MODULE_SOLID_EDGE + "_" + MINI;
	public static final String SOURCE_STANDARD_TARGET_WEST_MODULE_SOLID_EDGE_MINI = SOURCE_STANDARD_TARGET_WEST_MODULE_SOLID_EDGE + "_" + MINI;
	
	public static final String SOURCE_NORTH_SUBMODULE_TARGET_STANDARD_SOLID_EDGE_MINI = SOURCE_NORTH_SUBMODULE_TARGET_STANDARD_SOLID_EDGE + "_" + MINI;
	public static final String SOURCE_SOUTH_SUBMODULE_TARGET_STANDARD_SOLID_EDGE_MINI = SOURCE_SOUTH_SUBMODULE_TARGET_STANDARD_SOLID_EDGE + "_" + MINI;
	public static final String SOURCE_EAST_SUBMODULE_TARGET_STANDARD_SOLID_EDGE_MINI = SOURCE_EAST_SUBMODULE_TARGET_STANDARD_SOLID_EDGE + "_" + MINI;
	public static final String SOURCE_WEST_SUBMODULE_TARGET_STANDARD_SOLID_EDGE_MINI = SOURCE_WEST_SUBMODULE_TARGET_STANDARD_SOLID_EDGE + "_" + MINI;
	
	public static final String SOURCE_STANDARD_TARGET_NORTH_SUBMODULE_SOLID_EDGE_MINI = SOURCE_STANDARD_TARGET_NORTH_SUBMODULE_SOLID_EDGE + "_" + MINI;
	public static final String SOURCE_STANDARD_TARGET_SOUTH_SUBMODULE_SOLID_EDGE_MINI = SOURCE_STANDARD_TARGET_SOUTH_SUBMODULE_SOLID_EDGE + "_" + MINI;
	public static final String SOURCE_STANDARD_TARGET_EAST_SUBMODULE_SOLID_EDGE_MINI = SOURCE_STANDARD_TARGET_EAST_SUBMODULE_SOLID_EDGE + "_" + MINI;
	public static final String SOURCE_STANDARD_TARGET_WEST_SUBMODULE_SOLID_EDGE_MINI = SOURCE_STANDARD_TARGET_WEST_SUBMODULE_SOLID_EDGE + "_" + MINI;
	
	public static final String SOURCE_NORTH_MODULE_TARGET_STANDARD_DASHED_EDGE_MINI = SOURCE_NORTH_MODULE_TARGET_STANDARD_DASHED_EDGE + "_" + MINI;
	public static final String SOURCE_SOUTH_MODULE_TARGET_STANDARD_DASHED_EDGE_MINI = SOURCE_SOUTH_MODULE_TARGET_STANDARD_DASHED_EDGE + "_" + MINI;
	public static final String SOURCE_EAST_MODULE_TARGET_STANDARD_DASHED_EDGE_MINI = SOURCE_EAST_MODULE_TARGET_STANDARD_DASHED_EDGE + "_" + MINI;
	public static final String SOURCE_WEST_MODULE_TARGET_STANDARD_DASHED_EDGE_MINI = SOURCE_WEST_MODULE_TARGET_STANDARD_DASHED_EDGE + "_" + MINI;
	
	public static final String SOURCE_STANDARD_TARGET_NORTH_MODULE_DASHED_EDGE_MINI = SOURCE_STANDARD_TARGET_NORTH_MODULE_DASHED_EDGE + "_" + MINI;
	public static final String SOURCE_STANDARD_TARGET_SOUTH_MODULE_DASHED_EDGE_MINI = SOURCE_STANDARD_TARGET_SOUTH_MODULE_DASHED_EDGE + "_" + MINI;
	public static final String SOURCE_STANDARD_TARGET_EAST_MODULE_DASHED_EDGE_MINI = SOURCE_STANDARD_TARGET_EAST_MODULE_DASHED_EDGE + "_" + MINI;
	public static final String SOURCE_STANDARD_TARGET_WEST_MODULE_DASHED_EDGE_MINI = SOURCE_STANDARD_TARGET_WEST_MODULE_DASHED_EDGE + "_" + MINI;
	
	public static final String SOURCE_NORTH_SUBMODULE_TARGET_STANDARD_DASHED_EDGE_MINI = SOURCE_NORTH_SUBMODULE_TARGET_STANDARD_DASHED_EDGE + "_" + MINI;
	public static final String SOURCE_SOUTH_SUBMODULE_TARGET_STANDARD_DASHED_EDGE_MINI = SOURCE_SOUTH_SUBMODULE_TARGET_STANDARD_DASHED_EDGE + "_" + MINI;
	public static final String SOURCE_EAST_SUBMODULE_TARGET_STANDARD_DASHED_EDGE_MINI = SOURCE_EAST_SUBMODULE_TARGET_STANDARD_DASHED_EDGE + "_" + MINI;
	public static final String SOURCE_WEST_SUBMODULE_TARGET_STANDARD_DASHED_EDGE_MINI = SOURCE_WEST_SUBMODULE_TARGET_STANDARD_DASHED_EDGE + "_" + MINI;
	
	public static final String SOURCE_STANDARD_TARGET_NORTH_SUBMODULE_DASHED_EDGE_MINI = SOURCE_STANDARD_TARGET_NORTH_SUBMODULE_DASHED_EDGE + "_" + MINI;
	public static final String SOURCE_STANDARD_TARGET_SOUTH_SUBMODULE_DASHED_EDGE_MINI = SOURCE_STANDARD_TARGET_SOUTH_SUBMODULE_DASHED_EDGE + "_" + MINI;
	public static final String SOURCE_STANDARD_TARGET_EAST_SUBMODULE_DASHED_EDGE_MINI = SOURCE_STANDARD_TARGET_EAST_SUBMODULE_DASHED_EDGE + "_" + MINI;
	public static final String SOURCE_STANDARD_TARGET_WEST_SUBMODULE_DASHED_EDGE_MINI = SOURCE_STANDARD_TARGET_WEST_SUBMODULE_DASHED_EDGE + "_" + MINI;

}
