/* Generated By:JavaCC: Do not edit this line. MR_ChemicalReaction_ParserConstants.java */
package msmb.parsers.chemicalReaction;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MR_ChemicalReaction_ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 6;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 7;
  /** RegularExpression Id. */
  int EXPONENT = 8;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 9;
  /** RegularExpression Id. */
  int HEX_LITERAL = 10;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 11;
  /** RegularExpression Id. */
  int IDENTIFIER = 12;
  /** RegularExpression Id. */
  int DIGIT = 13;
  /** RegularExpression Id. */
  int STRING_LITERAL = 14;
  /** RegularExpression Id. */
  int LETTER = 15;
  /** RegularExpression Id. */
  int ARROW = 16;
  /** RegularExpression Id. */
  int ARROW2 = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 4>",
    "<token of kind 5>",
    "<INTEGER_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<IDENTIFIER>",
    "<DIGIT>",
    "<STRING_LITERAL>",
    "<LETTER>",
    "\" ->\"",
    "\"-> \"",
    "\" \"",
    "\";\"",
    "\" + \"",
    "\" * \"",
  };

}
