/* Generated by JTB 1.4.7 */
package msmb.parsers.multistateSpecies.syntaxtree;

import msmb.parsers.multistateSpecies.visitor.*;

/**
 * JTB node class for the production PossibleExtensions:<br>
 * Corresponding grammar:<br>
 * nodeChoice -> . %00 <EXTENSION_CONC><br>
 * .......... .. | %01 <EXTENSION_COMPARTMENT><br>
 * .......... .. | %02 <EXTENSION_PARTICLE><br>
 * .......... .. | %03 <EXTENSION_TRANS><br>
 * .......... .. | %04 <EXTENSION_INIT><br>
 * .......... .. | %05 <EXTENSION_RATE><br>
 * .......... .. | %06 <EXTENSION_SPECIES><br>
 * .......... .. | %07 <EXTENSION_GLOBALQ><br>
 * .......... .. | %08 <EXTENSION_FUNCTION><br>
 * .......... .. | %09 <EXTENSION_REACTION><br>
 * .......... .. | %10 <EXTENSION_FLUX><br>
 */
public class PossibleExtensions implements INode {

  /** Child node 1 */
  public NodeChoice nodeChoice;

  /** The serial version UID */
  private static final long serialVersionUID = 147L;

  /**
   * Constructs the node with its child node.
   *
   * @param n0 - the child node
   */
  public PossibleExtensions(final NodeChoice n0) {
    nodeChoice = n0;
  }

  /**
   * Accepts the IRetArguVisitor visitor.
   *
   * @param <R> the user return type
   * @param <A> the user argument type
   * @param vis - the visitor
   * @param argu - a user chosen argument
   * @return a user chosen return information
   */
  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  /**
   * Accepts the IRetVisitor visitor.
   *
   * @param <R> the user return type
   * @param vis - the visitor
   * @return a user chosen return information
   */
  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  /**
   * Accepts the IVoidArguVisitor visitor.
   *
   * @param <A> the user argument type
   * @param vis - the visitor
   * @param argu - a user chosen argument
   */
  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  /**
   * Accepts the IVoidVisitor visitor.
   *
   * @param vis - the visitor
   */
  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
