/* Generated By:JavaCC: Do not edit this line. MR_Expression_ParserTokenManager.java */
package msmb.parsers.mathExpression;
import msmb.parsers.mathExpression.syntaxtree.*;
import msmb.parsers.mathExpression.visitor.*;
import java.io.*;
import msmb.parsers.mathExpression.syntaxtree.*;

/** Token Manager. */
public class MR_Expression_ParserTokenManager implements MR_Expression_ParserConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x1ffe000000L) != 0L || (active1 & 0x4000000L) != 0L)
            return 10;
         if ((active0 & 0x1010000L) != 0L)
         {
            jjmatchedKind = 109;
            return 27;
         }
         if ((active0 & 0x880000000000L) != 0L)
         {
            jjmatchedKind = 109;
            return 7;
         }
         if ((active1 & 0x40000000L) != 0L)
            return 40;
         if ((active0 & 0x7fff776000fe0080L) != 0L || (active1 & 0x404000007ffL) != 0L)
         {
            jjmatchedKind = 109;
            return 24;
         }
         if ((active0 & 0x8000008000000000L) != 0L)
         {
            jjmatchedKind = 109;
            return 3;
         }
         return -1;
      case 1:
         if ((active0 & 0x80L) != 0L || (active1 & 0x440L) != 0L)
            return 24;
         if ((active0 & 0x8000000000000000L) != 0L)
         {
            jjmatchedKind = 109;
            jjmatchedPos = 1;
            return 2;
         }
         if ((active0 & 0x7fffffe001ff0000L) != 0L || (active1 & 0x404000003bfL) != 0L)
         {
            jjmatchedKind = 109;
            jjmatchedPos = 1;
            return 24;
         }
         return -1;
      case 2:
         if ((active0 & 0x1f8e2000ae0000L) != 0L || (active1 & 0x4040000033fL) != 0L)
            return 24;
         if ((active0 & 0xffe071c001510000L) != 0L || (active1 & 0x80L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 109;
               jjmatchedPos = 2;
            }
            return 24;
         }
         return -1;
      case 3:
         if ((active0 & 0x4011f10001510000L) != 0L)
            return 24;
         if ((active0 & 0xbfe000c000000000L) != 0L || (active1 & 0x84L) != 0L)
         {
            jjmatchedKind = 109;
            jjmatchedPos = 3;
            return 24;
         }
         return -1;
      case 4:
         if ((active0 & 0xc000000000L) != 0L || (active1 & 0x4L) != 0L)
            return 24;
         if ((active0 & 0xbfe0000000000000L) != 0L || (active1 & 0x80L) != 0L)
         {
            jjmatchedKind = 109;
            jjmatchedPos = 4;
            return 24;
         }
         return -1;
      case 5:
         if ((active0 & 0x38e0000000000000L) != 0L)
            return 24;
         if ((active0 & 0x8700000000000000L) != 0L || (active1 & 0x80L) != 0L)
         {
            if (jjmatchedPos != 5)
            {
               jjmatchedKind = 109;
               jjmatchedPos = 5;
            }
            return 24;
         }
         return -1;
      case 6:
         if ((active0 & 0x3f00000000000000L) != 0L)
            return 24;
         if ((active0 & 0x8000000000000000L) != 0L || (active1 & 0x80L) != 0L)
         {
            jjmatchedKind = 109;
            jjmatchedPos = 6;
            return 24;
         }
         return -1;
      case 7:
         if ((active0 & 0x8000000000000000L) != 0L || (active1 & 0x80L) != 0L)
         {
            jjmatchedKind = 109;
            jjmatchedPos = 7;
            return 24;
         }
         return -1;
      case 8:
         if ((active0 & 0x8000000000000000L) != 0L)
            return 24;
         if ((active1 & 0x80L) != 0L)
         {
            jjmatchedKind = 109;
            jjmatchedPos = 8;
            return 24;
         }
         return -1;
      case 9:
         if ((active1 & 0x80L) != 0L)
         {
            jjmatchedKind = 109;
            jjmatchedPos = 9;
            return 24;
         }
         return -1;
      case 10:
         if ((active1 & 0x80L) != 0L)
         {
            jjmatchedKind = 109;
            jjmatchedPos = 10;
            return 24;
         }
         return -1;
      case 11:
         if ((active1 & 0x80L) != 0L)
            return 24;
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 33:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x10000000000L);
      case 37:
         jjmatchedKind = 100;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x3800L);
      case 38:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x80000000000L);
      case 40:
         return jjStopAtPos(0, 81);
      case 41:
         return jjStopAtPos(0, 82);
      case 42:
         return jjStopAtPos(0, 93);
      case 43:
         return jjStopAtPos(0, 91);
      case 44:
         return jjStopAtPos(0, 88);
      case 45:
         return jjStopAtPos(0, 92);
      case 46:
         jjmatchedKind = 90;
         return jjMoveStringLiteralDfa1_0(0x1ffe000000L, 0x0L);
      case 47:
         return jjStartNfaWithStates_0(0, 94, 40);
      case 58:
         return jjStopAtPos(0, 89);
      case 59:
         return jjStopAtPos(0, 87);
      case 60:
         jjmatchedKind = 97;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x4000000000L);
      case 61:
         jjmatchedKind = 95;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x2000000000L);
      case 62:
         jjmatchedKind = 96;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x8000000000L);
      case 64:
         return jjStopAtPos(0, 108);
      case 69:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x80L);
      case 71:
         return jjMoveStringLiteralDfa1_0(0x20000L, 0x0L);
      case 77:
         return jjMoveStringLiteralDfa1_0(0x200000L, 0x0L);
      case 78:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x500L);
      case 80:
         return jjMoveStringLiteralDfa1_0(0x100000L, 0x40L);
      case 83:
         return jjMoveStringLiteralDfa1_0(0x2000480000L, 0x0L);
      case 84:
         return jjMoveStringLiteralDfa1_0(0x1010000L, 0x0L);
      case 86:
         return jjMoveStringLiteralDfa1_0(0x840000L, 0x0L);
      case 91:
         return jjStopAtPos(0, 85);
      case 93:
         return jjStopAtPos(0, 86);
      case 94:
         return jjStopAtPos(0, 99);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x3fe0700000000000L, 0x8L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0xd030000000000L, 0x0L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x4000000000L, 0x0L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x1L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x8000008000000000L, 0x0L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x80L, 0x0L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x6L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x30L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x400000200L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x4012040000000000L, 0x0L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x880000000000L, 0x0L);
      case 120:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x40000000000L);
      case 123:
         return jjStopAtPos(0, 83);
      case 124:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x20000000000L);
      case 125:
         return jjStopAtPos(0, 84);
      default :
         return jjMoveNfa_0(4, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0, long active1)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1);
      return 1;
   }
   switch(curChar)
   {
      case 38:
         if ((active1 & 0x80000000000L) != 0L)
            return jjStopAtPos(1, 107);
         break;
      case 42:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000000L, active1, 0L);
      case 61:
         if ((active1 & 0x2000000000L) != 0L)
            return jjStopAtPos(1, 101);
         else if ((active1 & 0x4000000000L) != 0L)
            return jjStopAtPos(1, 102);
         else if ((active1 & 0x8000000000L) != 0L)
            return jjStopAtPos(1, 103);
         else if ((active1 & 0x10000000000L) != 0L)
            return jjStopAtPos(1, 104);
         break;
      case 65:
         if ((active1 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(1, 74, 24);
         return jjMoveStringLiteralDfa2_0(active0, 0x40000L, active1, 0L);
      case 73:
         if ((active1 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(1, 70, 24);
         return jjMoveStringLiteralDfa2_0(active0, 0x1400000L, active1, 0L);
      case 76:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000L, active1, 0L);
      case 77:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x3000L);
      case 79:
         return jjMoveStringLiteralDfa2_0(active0, 0xa00000L, active1, 0L);
      case 81:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x800L);
      case 82:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000L, active1, 0L);
      case 85:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000080000L, active1, 0L);
      case 88:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x80L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000880000000000L, active1, 0x320L);
      case 98:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x8L);
      case 99:
         return jjMoveStringLiteralDfa2_0(active0, 0x100102000000L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x2014000000000L, active1, 0L);
      case 102:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(1, 7, 24);
         return jjMoveStringLiteralDfa2_0(active0, 0xc00000000L, active1, 0L);
      case 103:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x10040010010000L, active1, 0x10L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x9020000000000L, active1, 0x40400000006L);
      case 112:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000L, active1, 0L);
      case 113:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000000000000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x3fe0000220000000L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa2_0(active0, 0x4200040000000L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x400008000000L, active1, 0L);
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x1L);
      case 124:
         if ((active1 & 0x20000000000L) != 0L)
            return jjStopAtPos(1, 105);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(0, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1);
      return 2;
   }
   switch(curChar)
   {
      case 66:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(2, 19, 24);
         break;
      case 68:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(2, 21, 24);
         break;
      case 70:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x800L);
      case 76:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(2, 23, 24);
         break;
      case 77:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 37, 24);
         return jjMoveStringLiteralDfa3_0(active0, 0x1001000000L, active1, 0L);
      case 78:
         if ((active1 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(2, 72, 24);
         break;
      case 79:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000L, active1, 0L);
      case 80:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x80L);
      case 81:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(2, 17, 24);
         break;
      case 82:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(2, 18, 24);
         break;
      case 84:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000L, active1, 0L);
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x400020000000L, active1, 0L);
      case 99:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 49, 24);
         else if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 50, 24);
         return jjMoveStringLiteralDfa3_0(active0, 0xbfe0000200000000L, active1, 0L);
      case 103:
         if ((active1 & 0x2L) != 0L)
         {
            jjmatchedKind = 65;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x4L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x210000000000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x4880000000L, active1, 0L);
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x100010000L, active1, 0L);
      case 110:
         if ((active0 & 0x40000000000L) != 0L)
         {
            jjmatchedKind = 42;
            jjmatchedPos = 2;
         }
         else if ((active0 & 0x80000000000L) != 0L)
         {
            jjmatchedKind = 43;
            jjmatchedPos = 2;
         }
         else if ((active1 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(2, 68, 24);
         else if ((active1 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(2, 73, 24);
         return jjMoveStringLiteralDfa3_0(active0, 0x10800412000000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x108000000000L, active1, 0x3000L);
      case 112:
         if ((active1 & 0x1L) != 0L)
            return jjStartNfaWithStates_0(2, 64, 24);
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000L, active1, 0L);
      case 114:
         if ((active1 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 106, 24);
         return jjMoveStringLiteralDfa3_0(active0, 0x400000000c000000L, active1, 0L);
      case 115:
         if ((active0 & 0x20000000000L) != 0L)
         {
            jjmatchedKind = 41;
            jjmatchedPos = 2;
         }
         else if ((active1 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(2, 67, 24);
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000000000L, active1, 0L);
      case 116:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 51, 24);
         else if ((active1 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(2, 98, 24);
         break;
      case 120:
         if ((active1 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(2, 69, 24);
         break;
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(1, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1);
      return 3;
   }
   switch(curChar)
   {
      case 49:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x4L);
      case 67:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x800L);
      case 68:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(3, 20, 24);
         break;
      case 69:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(3, 22, 24);
         else if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(3, 24, 24);
         break;
      case 79:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x80L);
      case 89:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000000L, active1, 0L);
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000000L, active1, 0L);
      case 99:
         if ((active0 & 0x2000000L) != 0L)
            return jjStopAtPos(3, 25);
         else if ((active0 & 0x40000000L) != 0L)
            return jjStopAtPos(3, 30);
         else if ((active0 & 0x400000000L) != 0L)
            return jjStopAtPos(3, 34);
         return jjMoveStringLiteralDfa4_0(active0, 0x32c0000000000000L, active1, 0L);
      case 100:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x3000L);
      case 101:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(3, 16, 24);
         break;
      case 104:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 47, 24);
         else if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 48, 24);
         else if ((active0 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 52, 24);
         break;
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000L, active1, 0L);
      case 108:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 40, 24);
         break;
      case 110:
         if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 45, 24);
         else if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 46, 24);
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000000L, active1, 0L);
      case 112:
         if ((active0 & 0x100000000L) != 0L)
            return jjStopAtPos(3, 32);
         break;
      case 113:
         if ((active0 & 0x80000000L) != 0L)
            return jjStopAtPos(3, 31);
         break;
      case 115:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 44, 24);
         return jjMoveStringLiteralDfa4_0(active0, 0x920000000000000L, active1, 0L);
      case 116:
         if ((active0 & 0x4000000L) != 0L)
            return jjStopAtPos(3, 26);
         else if ((active0 & 0x200000000L) != 0L)
            return jjStopAtPos(3, 33);
         else if ((active0 & 0x4000000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 62, 24);
         return jjMoveStringLiteralDfa4_0(active0, 0x8400000020000000L, active1, 0L);
      case 120:
         if ((active0 & 0x800000000L) != 0L)
            return jjStopAtPos(3, 35);
         break;
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(2, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1);
      return 4;
   }
   switch(curChar)
   {
      case 37:
         if ((active1 & 0x800L) != 0L)
            return jjStopAtPos(4, 75);
         break;
      case 42:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000000L, active1, 0L);
      case 48:
         if ((active1 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(4, 66, 24);
         break;
      case 78:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x80L);
      case 84:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x3000L);
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x400000000000000L, active1, 0L);
      case 101:
         if ((active0 & 0x20000000L) != 0L)
            return jjStopAtPos(4, 29);
         return jjMoveStringLiteralDfa5_0(active0, 0x820000000000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x100000000000000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0xa280000000000000L, active1, 0L);
      case 114:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 39, 24);
         break;
      case 115:
         if ((active0 & 0x8000000L) != 0L)
            return jjStopAtPos(4, 27);
         return jjMoveStringLiteralDfa5_0(active0, 0x1040000000000000L, active1, 0L);
      case 116:
         if ((active0 & 0x10000000L) != 0L)
            return jjStopAtPos(4, 28);
         break;
      case 121:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 38, 24);
         break;
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(3, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, active1);
      return 5;
   }
   switch(curChar)
   {
      case 69:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x80L);
      case 83:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000000000L, active1, 0L);
      case 99:
         if ((active0 & 0x20000000000000L) != 0L)
         {
            jjmatchedKind = 53;
            jjmatchedPos = 5;
         }
         else if ((active0 & 0x40000000000000L) != 0L)
         {
            jjmatchedKind = 54;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x1800000000000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x3000L);
      case 110:
         return jjMoveStringLiteralDfa6_0(active0, 0x500000000000000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0x8000000000000000L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa6_0(active0, 0x200000000000000L, active1, 0L);
      case 116:
         if ((active0 & 0x80000000000000L) != 0L)
         {
            jjmatchedKind = 55;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0, active1);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(4, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, active1);
      return 6;
   }
   switch(curChar)
   {
      case 78:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x80L);
      case 80:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000000000L, active1, 0L);
      case 104:
         if ((active0 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 56, 24);
         else if ((active0 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 57, 24);
         else if ((active0 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 58, 24);
         else if ((active0 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 59, 24);
         else if ((active0 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 60, 24);
         else if ((active0 & 0x2000000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 61, 24);
         break;
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x8000000000000000L, active1, 0L);
      case 109:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x3000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0, active1);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(5, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, active1);
      return 7;
   }
   switch(curChar)
   {
      case 69:
         return jjMoveStringLiteralDfa8_0(active0, 0x1000000000L, active1, 0L);
      case 84:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x80L);
      case 97:
         return jjMoveStringLiteralDfa8_0(active0, 0x8000000000000000L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x3000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0, active1);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(6, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, active1);
      return 8;
   }
   switch(curChar)
   {
      case 37:
         if ((active1 & 0x1000L) != 0L)
            return jjStopAtPos(8, 76);
         break;
      case 46:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x2000L);
      case 67:
         return jjMoveStringLiteralDfa9_0(active0, 0x1000000000L, active1, 0L);
      case 73:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x80L);
      case 108:
         if ((active0 & 0x8000000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 63, 24);
         break;
      default :
         break;
   }
   return jjStartNfa_0(7, active0, active1);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(7, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, active1);
      return 9;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0x80L);
      case 73:
         return jjMoveStringLiteralDfa10_0(active0, 0x1000000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0x2000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0, active1);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(8, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0, active1);
      return 10;
   }
   switch(curChar)
   {
      case 37:
         if ((active1 & 0x2000L) != 0L)
            return jjStopAtPos(10, 77);
         break;
      case 65:
         return jjMoveStringLiteralDfa11_0(active0, 0x1000000000L, active1, 0L);
      case 76:
         return jjMoveStringLiteralDfa11_0(active0, 0L, active1, 0x80L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0, active1);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(9, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0, active1);
      return 11;
   }
   switch(curChar)
   {
      case 69:
         if ((active1 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(11, 71, 24);
         break;
      case 76:
         return jjMoveStringLiteralDfa12_0(active0, 0x1000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0, active1);
}
private int jjMoveStringLiteralDfa12_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(10, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0, 0L);
      return 12;
   }
   switch(curChar)
   {
      case 42:
         return jjMoveStringLiteralDfa13_0(active0, 0x1000000000L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0, 0L);
}
private int jjMoveStringLiteralDfa13_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0, 0L);
      return 13;
   }
   switch(curChar)
   {
      case 69:
         return jjMoveStringLiteralDfa14_0(active0, 0x1000000000L);
      default :
         break;
   }
   return jjStartNfa_0(12, active0, 0L);
}
private int jjMoveStringLiteralDfa14_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(12, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0, 0L);
      return 14;
   }
   switch(curChar)
   {
      case 88:
         return jjMoveStringLiteralDfa15_0(active0, 0x1000000000L);
      default :
         break;
   }
   return jjStartNfa_0(13, active0, 0L);
}
private int jjMoveStringLiteralDfa15_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(13, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, active0, 0L);
      return 15;
   }
   switch(curChar)
   {
      case 84:
         return jjMoveStringLiteralDfa16_0(active0, 0x1000000000L);
      default :
         break;
   }
   return jjStartNfa_0(14, active0, 0L);
}
private int jjMoveStringLiteralDfa16_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(14, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(15, active0, 0L);
      return 16;
   }
   switch(curChar)
   {
      case 69:
         return jjMoveStringLiteralDfa17_0(active0, 0x1000000000L);
      default :
         break;
   }
   return jjStartNfa_0(15, active0, 0L);
}
private int jjMoveStringLiteralDfa17_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(15, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(16, active0, 0L);
      return 17;
   }
   switch(curChar)
   {
      case 78:
         return jjMoveStringLiteralDfa18_0(active0, 0x1000000000L);
      default :
         break;
   }
   return jjStartNfa_0(16, active0, 0L);
}
private int jjMoveStringLiteralDfa18_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(16, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(17, active0, 0L);
      return 18;
   }
   switch(curChar)
   {
      case 83:
         return jjMoveStringLiteralDfa19_0(active0, 0x1000000000L);
      default :
         break;
   }
   return jjStartNfa_0(17, active0, 0L);
}
private int jjMoveStringLiteralDfa19_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(17, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(18, active0, 0L);
      return 19;
   }
   switch(curChar)
   {
      case 73:
         return jjMoveStringLiteralDfa20_0(active0, 0x1000000000L);
      default :
         break;
   }
   return jjStartNfa_0(18, active0, 0L);
}
private int jjMoveStringLiteralDfa20_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(18, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(19, active0, 0L);
      return 20;
   }
   switch(curChar)
   {
      case 79:
         return jjMoveStringLiteralDfa21_0(active0, 0x1000000000L);
      default :
         break;
   }
   return jjStartNfa_0(19, active0, 0L);
}
private int jjMoveStringLiteralDfa21_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(19, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(20, active0, 0L);
      return 21;
   }
   switch(curChar)
   {
      case 78:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStopAtPos(21, 36);
         break;
      default :
         break;
   }
   return jjStartNfa_0(20, active0, 0L);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec1 = {
   0x0L, 0xffff000000000000L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 67;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 40:
                  if (curChar == 42)
                     jjCheckNAddTwoStates(46, 47);
                  else if (curChar == 47)
                     jjCheckNAddStates(0, 2);
                  break;
               case 4:
                  if ((0x3ff008000000000L & l) != 0L)
                  {
                     if (kind > 109)
                        kind = 109;
                     jjCheckNAdd(24);
                  }
                  else if (curChar == 47)
                     jjAddStates(3, 4);
                  else if (curChar == 34)
                     jjCheckNAddStates(5, 7);
                  else if (curChar == 46)
                     jjCheckNAdd(10);
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 78)
                        kind = 78;
                     jjCheckNAddStates(8, 15);
                  }
                  break;
               case 7:
               case 24:
                  if ((0x3ff008000000000L & l) == 0L)
                     break;
                  if (kind > 109)
                     kind = 109;
                  jjCheckNAdd(24);
                  break;
               case 3:
                  if ((0x3ff008000000000L & l) == 0L)
                     break;
                  if (kind > 109)
                     kind = 109;
                  jjCheckNAdd(24);
                  break;
               case 2:
                  if ((0x3ff008000000000L & l) == 0L)
                     break;
                  if (kind > 109)
                     kind = 109;
                  jjCheckNAdd(24);
                  break;
               case 27:
                  if ((0x3ff008000000000L & l) == 0L)
                     break;
                  if (kind > 109)
                     kind = 109;
                  jjCheckNAdd(24);
                  break;
               case 9:
                  if (curChar == 46)
                     jjCheckNAdd(10);
                  break;
               case 10:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 79)
                     kind = 79;
                  jjCheckNAddStates(16, 18);
                  break;
               case 12:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(13);
                  break;
               case 13:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 79)
                     kind = 79;
                  jjCheckNAddTwoStates(13, 14);
                  break;
               case 15:
                  if (curChar == 34)
                     jjCheckNAddStates(5, 7);
                  break;
               case 16:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     jjCheckNAddStates(5, 7);
                  break;
               case 18:
                  if ((0x8400000000L & l) != 0L)
                     jjCheckNAddStates(5, 7);
                  break;
               case 19:
                  if (curChar == 34 && kind > 109)
                     kind = 109;
                  break;
               case 20:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(19, 22);
                  break;
               case 21:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(5, 7);
                  break;
               case 22:
                  if ((0xf000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 23:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAdd(21);
                  break;
               case 39:
                  if (curChar == 47)
                     jjAddStates(3, 4);
                  break;
               case 41:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  break;
               case 42:
                  if ((0x2400L & l) != 0L && kind > 5)
                     kind = 5;
                  break;
               case 43:
                  if (curChar == 10 && kind > 5)
                     kind = 5;
                  break;
               case 44:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 45:
                  if (curChar == 42)
                     jjCheckNAddTwoStates(46, 47);
                  break;
               case 46:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(46, 47);
                  break;
               case 47:
                  if (curChar == 42)
                     jjAddStates(23, 24);
                  break;
               case 48:
                  if ((0xffff7fffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(49, 47);
                  break;
               case 49:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(49, 47);
                  break;
               case 50:
                  if (curChar == 47 && kind > 6)
                     kind = 6;
                  break;
               case 51:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 78)
                     kind = 78;
                  jjCheckNAddStates(8, 15);
                  break;
               case 52:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 78)
                     kind = 78;
                  jjCheckNAdd(52);
                  break;
               case 53:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(53, 54);
                  break;
               case 54:
                  if (curChar != 46)
                     break;
                  if (kind > 79)
                     kind = 79;
                  jjCheckNAddStates(25, 27);
                  break;
               case 55:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 79)
                     kind = 79;
                  jjCheckNAddStates(25, 27);
                  break;
               case 57:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(58);
                  break;
               case 58:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 79)
                     kind = 79;
                  jjCheckNAddTwoStates(58, 14);
                  break;
               case 59:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(59, 60);
                  break;
               case 61:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(62);
                  break;
               case 62:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 79)
                     kind = 79;
                  jjCheckNAddTwoStates(62, 14);
                  break;
               case 63:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(28, 30);
                  break;
               case 65:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(66);
                  break;
               case 66:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(66, 14);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 4:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 109)
                        kind = 109;
                     jjCheckNAdd(24);
                  }
                  if (curChar == 70)
                     jjAddStates(31, 32);
                  else if (curChar == 84)
                     jjAddStates(33, 34);
                  else if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 7;
                  else if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 7:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 109)
                        kind = 109;
                     jjCheckNAdd(24);
                  }
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 3:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 109)
                        kind = 109;
                     jjCheckNAdd(24);
                  }
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 2:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 109)
                        kind = 109;
                     jjCheckNAdd(24);
                  }
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 27:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 109)
                        kind = 109;
                     jjCheckNAdd(24);
                  }
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 29;
                  else if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 0:
                  if (curChar == 101 && kind > 8)
                     kind = 8;
                  break;
               case 1:
               case 32:
                  if (curChar == 115)
                     jjCheckNAdd(0);
                  break;
               case 5:
                  if (curChar == 101 && kind > 9)
                     kind = 9;
                  break;
               case 6:
               case 26:
                  if (curChar == 117)
                     jjCheckNAdd(5);
                  break;
               case 8:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 11:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(35, 36);
                  break;
               case 14:
                  if ((0x5000000050L & l) != 0L && kind > 79)
                     kind = 79;
                  break;
               case 16:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(5, 7);
                  break;
               case 17:
                  if (curChar == 92)
                     jjAddStates(37, 39);
                  break;
               case 18:
                  if ((0x14404410000000L & l) != 0L)
                     jjCheckNAddStates(5, 7);
                  break;
               case 24:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 109)
                     kind = 109;
                  jjCheckNAdd(24);
                  break;
               case 25:
                  if (curChar == 84)
                     jjAddStates(33, 34);
                  break;
               case 28:
                  if (curChar == 69 && kind > 9)
                     kind = 9;
                  break;
               case 29:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 30:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 31:
                  if (curChar == 70)
                     jjAddStates(31, 32);
                  break;
               case 33:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 34:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 35:
                  if (curChar == 69 && kind > 8)
                     kind = 8;
                  break;
               case 36:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 37:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 38:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 41:
                  jjAddStates(0, 2);
                  break;
               case 46:
                  jjCheckNAddTwoStates(46, 47);
                  break;
               case 48:
               case 49:
                  jjCheckNAddTwoStates(49, 47);
                  break;
               case 56:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(40, 41);
                  break;
               case 60:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(42, 43);
                  break;
               case 64:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(44, 45);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 4:
               case 24:
                  if (!jjCanMove_1(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 109)
                     kind = 109;
                  jjCheckNAdd(24);
                  break;
               case 7:
                  if (!jjCanMove_1(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 109)
                     kind = 109;
                  jjCheckNAdd(24);
                  break;
               case 3:
                  if (!jjCanMove_1(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 109)
                     kind = 109;
                  jjCheckNAdd(24);
                  break;
               case 2:
                  if (!jjCanMove_1(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 109)
                     kind = 109;
                  jjCheckNAdd(24);
                  break;
               case 27:
                  if (!jjCanMove_1(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 109)
                     kind = 109;
                  jjCheckNAdd(24);
                  break;
               case 16:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(5, 7);
                  break;
               case 41:
                  if (jjCanMove_2(hiByte, i1, i2, l1, l2))
                     jjAddStates(0, 2);
                  break;
               case 46:
                  if (jjCanMove_2(hiByte, i1, i2, l1, l2))
                     jjCheckNAddTwoStates(46, 47);
                  break;
               case 48:
               case 49:
                  if (jjCanMove_2(hiByte, i1, i2, l1, l2))
                     jjCheckNAddTwoStates(49, 47);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 67 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   41, 42, 44, 40, 45, 16, 17, 19, 52, 53, 54, 59, 60, 63, 64, 14, 
   10, 11, 14, 16, 17, 21, 19, 48, 50, 55, 56, 14, 63, 64, 14, 34, 
   38, 27, 30, 12, 13, 18, 20, 22, 57, 58, 61, 62, 65, 66, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec0[i2] & l2) != 0L);
      case 3:
         return ((jjbitVec1[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_1(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 3:
         return ((jjbitVec1[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_2(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec0[i2] & l2) != 0L);
      default :
         return false;
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, "\151\146", null, null, null, null, 
null, null, null, null, "\124\151\155\145", "\107\114\121", "\126\101\122", 
"\123\125\102", "\120\122\117\104", "\115\117\104", "\123\111\124\105", "\126\117\114", 
"\124\111\115\105", "\56\143\156\143", "\56\160\162\164", "\56\164\162\156\163", 
"\56\151\156\151\164", "\56\162\141\164\145", "\56\163\160\143", "\56\147\154\161", 
"\56\143\155\160", "\56\162\143\164", "\56\146\156\143", "\56\146\154\170", 
"\56\52\115\131\52\123\120\105\103\111\101\114\52\105\130\124\105\116\123\111\117\116", "\123\125\115", "\144\145\154\141\171", "\146\154\157\157\162", 
"\143\145\151\154", "\143\157\163", "\163\151\156", "\164\141\156", "\141\143\157\163", 
"\141\163\151\156", "\141\164\141\156", "\164\141\156\150", "\143\157\163\150", "\163\145\143", 
"\143\163\143", "\143\157\164", "\163\151\156\150", "\141\162\143\163\145\143", 
"\141\162\143\143\163\143", "\141\162\143\143\157\164", "\141\162\143\163\151\156\150", 
"\141\162\143\143\157\163\150", "\141\162\143\164\141\156\150", "\141\162\143\163\145\143\150", 
"\141\162\143\143\163\143\150", "\141\162\143\143\157\164\150", "\163\161\162\164", 
"\146\141\143\164\157\162\151\141\154", "\145\170\160", "\154\157\147", "\154\157\147\61\60", "\141\142\163", 
"\155\151\156", "\155\141\170", "\120\111", 
"\105\130\120\117\116\105\116\124\111\101\114\105", "\116\141\116", "\156\141\156", "\116\101", "\45\121\106\103\45", 
"\45\115\157\144\124\151\155\145\45", "\45\115\157\144\124\151\155\145\56\151\45", null, null, null, "\50", "\51", 
"\173", "\175", "\133", "\135", "\73", "\54", "\72", "\56", "\53", "\55", "\52", 
"\57", "\75", "\76", "\74", "\156\157\164", "\136", "\45", "\75\75", "\74\75", 
"\76\75", "\41\75", "\174\174", "\170\157\162", "\46\46", "\100", null, null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xffffffffffff0381L, 0x3ffffffeffffL, 
};
static final long[] jjtoSkip = {
   0x7eL, 0x0L, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[67];
private final int[] jjstateSet = new int[134];
protected char curChar;
/** Constructor. */
public MR_Expression_ParserTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public MR_Expression_ParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 67; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
