/* Generated By:JavaCC: Do not edit this line. MR_Expression_ParserConstants.java */
package msmb.parsers.mathExpression;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MR_Expression_ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 7;
  /** RegularExpression Id. */
  int FALSE = 8;
  /** RegularExpression Id. */
  int TRUE = 9;
  /** RegularExpression Id. */
  int TRUE_1 = 10;
  /** RegularExpression Id. */
  int TRUE_2 = 11;
  /** RegularExpression Id. */
  int TRUE_3 = 12;
  /** RegularExpression Id. */
  int FALSE_1 = 13;
  /** RegularExpression Id. */
  int FALSE_2 = 14;
  /** RegularExpression Id. */
  int FALSE_3 = 15;
  /** RegularExpression Id. */
  int TIME = 16;
  /** RegularExpression Id. */
  int TYPE_PAR = 17;
  /** RegularExpression Id. */
  int TYPE_VAR = 18;
  /** RegularExpression Id. */
  int TYPE_SUB = 19;
  /** RegularExpression Id. */
  int TYPE_PROD = 20;
  /** RegularExpression Id. */
  int TYPE_MOD = 21;
  /** RegularExpression Id. */
  int TYPE_SITE = 22;
  /** RegularExpression Id. */
  int TYPE_VOL = 23;
  /** RegularExpression Id. */
  int TYPE_TIME = 24;
  /** RegularExpression Id. */
  int EXTENSION_CONC = 25;
  /** RegularExpression Id. */
  int EXTENSION_PARTICLE = 26;
  /** RegularExpression Id. */
  int EXTENSION_TRANS = 27;
  /** RegularExpression Id. */
  int EXTENSION_INIT = 28;
  /** RegularExpression Id. */
  int EXTENSION_RATE = 29;
  /** RegularExpression Id. */
  int EXTENSION_SPECIES = 30;
  /** RegularExpression Id. */
  int EXTENSION_GLOBALQ = 31;
  /** RegularExpression Id. */
  int EXTENSION_COMPARTMENT = 32;
  /** RegularExpression Id. */
  int EXTENSION_REACTION = 33;
  /** RegularExpression Id. */
  int EXTENSION_FUNCTION = 34;
  /** RegularExpression Id. */
  int EXTENSION_FLUX = 35;
  /** RegularExpression Id. */
  int MY_SPECIAL_EXTENSION = 36;
  /** RegularExpression Id. */
  int SUM = 37;
  /** RegularExpression Id. */
  int DELAY = 38;
  /** RegularExpression Id. */
  int FLOOR = 39;
  /** RegularExpression Id. */
  int CEIL = 40;
  /** RegularExpression Id. */
  int COS = 41;
  /** RegularExpression Id. */
  int SIN = 42;
  /** RegularExpression Id. */
  int TAN = 43;
  /** RegularExpression Id. */
  int ACOS = 44;
  /** RegularExpression Id. */
  int ASIN = 45;
  /** RegularExpression Id. */
  int ATAN = 46;
  /** RegularExpression Id. */
  int TANH = 47;
  /** RegularExpression Id. */
  int COSH = 48;
  /** RegularExpression Id. */
  int SEC = 49;
  /** RegularExpression Id. */
  int CSC = 50;
  /** RegularExpression Id. */
  int COT = 51;
  /** RegularExpression Id. */
  int SINH = 52;
  /** RegularExpression Id. */
  int ARCSEC = 53;
  /** RegularExpression Id. */
  int ARCCSC = 54;
  /** RegularExpression Id. */
  int ARCCOT = 55;
  /** RegularExpression Id. */
  int ARCSINH = 56;
  /** RegularExpression Id. */
  int ARCCOSH = 57;
  /** RegularExpression Id. */
  int ARCTANH = 58;
  /** RegularExpression Id. */
  int ARCSECH = 59;
  /** RegularExpression Id. */
  int ARCCSCH = 60;
  /** RegularExpression Id. */
  int ARCCOTH = 61;
  /** RegularExpression Id. */
  int SQRT = 62;
  /** RegularExpression Id. */
  int FACTORIAL = 63;
  /** RegularExpression Id. */
  int EXP = 64;
  /** RegularExpression Id. */
  int LOG = 65;
  /** RegularExpression Id. */
  int LOG10 = 66;
  /** RegularExpression Id. */
  int ABS = 67;
  /** RegularExpression Id. */
  int MIN = 68;
  /** RegularExpression Id. */
  int MAX = 69;
  /** RegularExpression Id. */
  int PI = 70;
  /** RegularExpression Id. */
  int EXPONENTIALE = 71;
  /** RegularExpression Id. */
  int NAN1 = 72;
  /** RegularExpression Id. */
  int NAN2 = 73;
  /** RegularExpression Id. */
  int CONST_AVOGADRO = 74;
  /** RegularExpression Id. */
  int CONST_QUANTITY_CONV_FACTOR = 75;
  /** RegularExpression Id. */
  int CONST_MODEL_TIME = 76;
  /** RegularExpression Id. */
  int CONST_MODEL_TIME_INITIAL = 77;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 78;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 79;
  /** RegularExpression Id. */
  int EXPONENT = 80;
  /** RegularExpression Id. */
  int LPAREN = 81;
  /** RegularExpression Id. */
  int RPAREN = 82;
  /** RegularExpression Id. */
  int LBRACE = 83;
  /** RegularExpression Id. */
  int RBRACE = 84;
  /** RegularExpression Id. */
  int LBRACKET = 85;
  /** RegularExpression Id. */
  int RBRACKET = 86;
  /** RegularExpression Id. */
  int SEMICOLON = 87;
  /** RegularExpression Id. */
  int COMMA = 88;
  /** RegularExpression Id. */
  int COLON = 89;
  /** RegularExpression Id. */
  int DOT = 90;
  /** RegularExpression Id. */
  int PLUS = 91;
  /** RegularExpression Id. */
  int MINUS = 92;
  /** RegularExpression Id. */
  int TIMES = 93;
  /** RegularExpression Id. */
  int DIV = 94;
  /** RegularExpression Id. */
  int ASSIGN = 95;
  /** RegularExpression Id. */
  int GT = 96;
  /** RegularExpression Id. */
  int LT = 97;
  /** RegularExpression Id. */
  int BANG = 98;
  /** RegularExpression Id. */
  int CARET = 99;
  /** RegularExpression Id. */
  int PERC = 100;
  /** RegularExpression Id. */
  int EQ = 101;
  /** RegularExpression Id. */
  int LEQ = 102;
  /** RegularExpression Id. */
  int GEQ = 103;
  /** RegularExpression Id. */
  int NE = 104;
  /** RegularExpression Id. */
  int OR = 105;
  /** RegularExpression Id. */
  int XOR = 106;
  /** RegularExpression Id. */
  int AND = 107;
  /** RegularExpression Id. */
  int MUTANT_PARENT_SEPARATOR = 108;
  /** RegularExpression Id. */
  int IDENTIFIER = 109;
  /** RegularExpression Id. */
  int LETTER = 110;
  /** RegularExpression Id. */
  int DIGIT = 111;
  /** RegularExpression Id. */
  int STRING_LITERAL = 112;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"if\"",
    "<FALSE>",
    "<TRUE>",
    "\"true\"",
    "\"True\"",
    "\"TRUE\"",
    "\"false\"",
    "\"False\"",
    "\"FALSE\"",
    "\"Time\"",
    "\"GLQ\"",
    "\"VAR\"",
    "\"SUB\"",
    "\"PROD\"",
    "\"MOD\"",
    "\"SITE\"",
    "\"VOL\"",
    "\"TIME\"",
    "\".cnc\"",
    "\".prt\"",
    "\".trns\"",
    "\".init\"",
    "\".rate\"",
    "\".spc\"",
    "\".glq\"",
    "\".cmp\"",
    "\".rct\"",
    "\".fnc\"",
    "\".flx\"",
    "\".*MY*SPECIAL*EXTENSION\"",
    "\"SUM\"",
    "\"delay\"",
    "\"floor\"",
    "\"ceil\"",
    "\"cos\"",
    "\"sin\"",
    "\"tan\"",
    "\"acos\"",
    "\"asin\"",
    "\"atan\"",
    "\"tanh\"",
    "\"cosh\"",
    "\"sec\"",
    "\"csc\"",
    "\"cot\"",
    "\"sinh\"",
    "\"arcsec\"",
    "\"arccsc\"",
    "\"arccot\"",
    "\"arcsinh\"",
    "\"arccosh\"",
    "\"arctanh\"",
    "\"arcsech\"",
    "\"arccsch\"",
    "\"arccoth\"",
    "\"sqrt\"",
    "\"factorial\"",
    "\"exp\"",
    "\"log\"",
    "\"log10\"",
    "\"abs\"",
    "\"min\"",
    "\"max\"",
    "\"PI\"",
    "\"EXPONENTIALE\"",
    "\"NaN\"",
    "\"nan\"",
    "\"NA\"",
    "\"%QFC%\"",
    "\"%ModTime%\"",
    "\"%ModTime.i%\"",
    "<INTEGER_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\":\"",
    "\".\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"not\"",
    "\"^\"",
    "\"%\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"xor\"",
    "\"&&\"",
    "\"@\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<STRING_LITERAL>",
  };

}
